server:
  ## Declare the port for the User entitlement microservices
  port: 8081
  ## if got error send in the response of the controller as message
  error:
    include-message: ALWAYS

spring:
  ## Declare the active and default profiles
  profiles:
    active: dev
    default: dev
  ## Declare the application name
  application:
    name: ms-users-entitlement
  output:
    ansi:
      enabled: ALWAYS

eureka:
  ## Enable the client for eureka to register and fetch the registry
  client:
    fetch-registry: true
    enabled: true
    register-with-eureka: true

springdoc:
  swagger-ui:
    path: "/api/entitlement/swagger/swagger-ui.html"
  api-docs:
    path: "/api/entitlement/v3/api-docs"

application.version: @project.version@