spring:
  ## Declare the H2 database as a file for local development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microservices
    username: chakarai1234
    password: password
  ## enable the h2 console
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  ## Enable the
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    ## generate the Date definition language
    generate-ddl: true
    ## Create and drop after the instance so that every start is fresh clean slate
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include:
          - "*"





