
spring:
  profiles:
    active: dev
    default: dev
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: USERS-ENTITLEMENT

eureka:
  client:
    enabled: true
    register-with-eureka: true
